name: deploy workshop

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    container: rocker/verse:latest
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: remotes

      - name: Build presentation parts
        run: |
          rmarkdown::render("index.Rmd", "all")
          rmarkdown::render("_01_shiny_intro.Rmd", "all")
          rmarkdown::render("_02_shiny_mini.Rmd", "all")
          rmarkdown::render("_04_shiny_in_prod.Rmd", "all")
        shell: Rscript {0}

      - name: Build the entire presentation
        run: |
            rmarkdown::render("cws_shiny_workshop.Rmd", "all")
        shell: Rscript {0}
        
      - name: Build data and script 
        run: |
          knitr::purl("cws_shiny_workshop.Rmd", "script.R")
          zip("data_and_script.zip", c("data", "script.R"))
        shell: Rscript {0}

      - name: Deploy workshop slides
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.DEPLOY_TOKEN }}
          publish_dir: .
          exclude_assets: '.github,.gitignore,DESCRIPTION,makefile'
